/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__android_net_LocalServerSocket__H
#define J4A__android_net_LocalServerSocket__H

#include "j4a/j4a_base.h"

jobject J4AC_android_net_LocalServerSocket__LocalServerSocket(JNIEnv *env, jstring name);
jobject J4AC_android_net_LocalServerSocket__LocalServerSocket__catchAll(JNIEnv *env, jstring name);
jobject J4AC_android_net_LocalServerSocket__LocalServerSocket__asGlobalRef__catchAll(JNIEnv *env, jstring name);
jobject J4AC_android_net_LocalServerSocket__LocalServerSocket__withCString(JNIEnv *env, const char *name_cstr__);
jobject J4AC_android_net_LocalServerSocket__LocalServerSocket__withCString__catchAll(JNIEnv *env, const char *name_cstr__);
jobject J4AC_android_net_LocalServerSocket__LocalServerSocket__withCString__asGlobalRef__catchAll(JNIEnv *env, const char *name_cstr__);
jobject J4AC_android_net_LocalServerSocket__getLocalSocketAddress(JNIEnv *env, jobject thiz);
jobject J4AC_android_net_LocalServerSocket__getLocalSocketAddress__catchAll(JNIEnv *env, jobject thiz);
jobject J4AC_android_net_LocalServerSocket__getLocalSocketAddress__asGlobalRef__catchAll(JNIEnv *env, jobject thiz);
jobject J4AC_android_net_LocalServerSocket__accept(JNIEnv *env, jobject thiz);
jobject J4AC_android_net_LocalServerSocket__accept__catchAll(JNIEnv *env, jobject thiz);
jobject J4AC_android_net_LocalServerSocket__accept__asGlobalRef__catchAll(JNIEnv *env, jobject thiz);
void J4AC_android_net_LocalServerSocket__close(JNIEnv *env, jobject thiz);
void J4AC_android_net_LocalServerSocket__close__catchAll(JNIEnv *env, jobject thiz);
int J4A_loadClass__J4AC_android_net_LocalServerSocket(JNIEnv *env);

#define J4A_HAVE_SIMPLE__J4AC_android_net_LocalServerSocket

#define J4AC_LocalServerSocket__LocalServerSocket J4AC_android_net_LocalServerSocket__LocalServerSocket
#define J4AC_LocalServerSocket__LocalServerSocket__asGlobalRef__catchAll J4AC_android_net_LocalServerSocket__LocalServerSocket__asGlobalRef__catchAll
#define J4AC_LocalServerSocket__LocalServerSocket__catchAll J4AC_android_net_LocalServerSocket__LocalServerSocket__catchAll
#define J4AC_LocalServerSocket__LocalServerSocket__withCString J4AC_android_net_LocalServerSocket__LocalServerSocket__withCString
#define J4AC_LocalServerSocket__LocalServerSocket__withCString__asGlobalRef__catchAll J4AC_android_net_LocalServerSocket__LocalServerSocket__withCString__asGlobalRef__catchAll
#define J4AC_LocalServerSocket__LocalServerSocket__withCString__catchAll J4AC_android_net_LocalServerSocket__LocalServerSocket__withCString__catchAll
#define J4AC_LocalServerSocket__getLocalSocketAddress J4AC_android_net_LocalServerSocket__getLocalSocketAddress
#define J4AC_LocalServerSocket__getLocalSocketAddress__asGlobalRef__catchAll J4AC_android_net_LocalServerSocket__getLocalSocketAddress__asGlobalRef__catchAll
#define J4AC_LocalServerSocket__getLocalSocketAddress__catchAll J4AC_android_net_LocalServerSocket__getLocalSocketAddress__catchAll
#define J4AC_LocalServerSocket__accept J4AC_android_net_LocalServerSocket__accept
#define J4AC_LocalServerSocket__accept__asGlobalRef__catchAll J4AC_android_net_LocalServerSocket__accept__asGlobalRef__catchAll
#define J4AC_LocalServerSocket__accept__catchAll J4AC_android_net_LocalServerSocket__accept__catchAll
#define J4AC_LocalServerSocket__close J4AC_android_net_LocalServerSocket__close
#define J4AC_LocalServerSocket__close__catchAll J4AC_android_net_LocalServerSocket__close__catchAll
#define J4A_loadClass__J4AC_LocalServerSocket J4A_loadClass__J4AC_android_net_LocalServerSocket

#endif//J4A__android_net_LocalServerSocket__H
