/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "LocalServerSocket.h"

typedef struct J4AC_android_net_LocalServerSocket {
    jclass id;

    jmethodID constructor_LocalServerSocket;
    jmethodID method_getLocalSocketAddress;
    jmethodID method_accept;
    jmethodID method_close;
} J4AC_android_net_LocalServerSocket;
static J4AC_android_net_LocalServerSocket class_J4AC_android_net_LocalServerSocket;

jobject J4AC_android_net_LocalServerSocket__LocalServerSocket(JNIEnv *env, jstring name)
{
    return (*env)->NewObject(env, class_J4AC_android_net_LocalServerSocket.id, class_J4AC_android_net_LocalServerSocket.constructor_LocalServerSocket, name);
}

jobject J4AC_android_net_LocalServerSocket__LocalServerSocket__catchAll(JNIEnv *env, jstring name)
{
    jobject ret_object = J4AC_android_net_LocalServerSocket__LocalServerSocket(env, name);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_android_net_LocalServerSocket__LocalServerSocket__asGlobalRef__catchAll(JNIEnv *env, jstring name)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_android_net_LocalServerSocket__LocalServerSocket__catchAll(env, name);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jobject J4AC_android_net_LocalServerSocket__LocalServerSocket__withCString(JNIEnv *env, const char *name_cstr__)
{
    jobject ret_object = NULL;
    jstring name = NULL;

    name = (*env)->NewStringUTF(env, name_cstr__);
    if (J4A_ExceptionCheck__throwAny(env) || !name)
        goto fail;

    ret_object = J4AC_android_net_LocalServerSocket__LocalServerSocket(env, name);
    if (J4A_ExceptionCheck__throwAny(env) || !ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &name);
    return ret_object;
}

jobject J4AC_android_net_LocalServerSocket__LocalServerSocket__withCString__catchAll(JNIEnv *env, const char *name_cstr__)
{
    jobject ret_object = NULL;
    jstring name = NULL;

    name = (*env)->NewStringUTF(env, name_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !name)
        goto fail;

    ret_object = J4AC_android_net_LocalServerSocket__LocalServerSocket__catchAll(env, name);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &name);
    return ret_object;
}

jobject J4AC_android_net_LocalServerSocket__LocalServerSocket__withCString__asGlobalRef__catchAll(JNIEnv *env, const char *name_cstr__)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_android_net_LocalServerSocket__LocalServerSocket__withCString__catchAll(env, name_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jobject J4AC_android_net_LocalServerSocket__getLocalSocketAddress(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_android_net_LocalServerSocket.method_getLocalSocketAddress);
}

jobject J4AC_android_net_LocalServerSocket__getLocalSocketAddress__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object = J4AC_android_net_LocalServerSocket__getLocalSocketAddress(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_android_net_LocalServerSocket__getLocalSocketAddress__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_android_net_LocalServerSocket__getLocalSocketAddress__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jobject J4AC_android_net_LocalServerSocket__accept(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_android_net_LocalServerSocket.method_accept);
}

jobject J4AC_android_net_LocalServerSocket__accept__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object = J4AC_android_net_LocalServerSocket__accept(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_android_net_LocalServerSocket__accept__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_android_net_LocalServerSocket__accept__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

void J4AC_android_net_LocalServerSocket__close(JNIEnv *env, jobject thiz)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_android_net_LocalServerSocket.method_close);
}

void J4AC_android_net_LocalServerSocket__close__catchAll(JNIEnv *env, jobject thiz)
{
    J4AC_android_net_LocalServerSocket__close(env, thiz);
    J4A_ExceptionCheck__catchAll(env);
}

int J4A_loadClass__J4AC_android_net_LocalServerSocket(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_android_net_LocalServerSocket.id != NULL)
        return 0;

    sign = "android/net/LocalServerSocket";
    class_J4AC_android_net_LocalServerSocket.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_android_net_LocalServerSocket.id == NULL)
        goto fail;

    class_id = class_J4AC_android_net_LocalServerSocket.id;
    name     = "<init>";
    sign     = "(Ljava/lang/String;)V";
    class_J4AC_android_net_LocalServerSocket.constructor_LocalServerSocket = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_net_LocalServerSocket.constructor_LocalServerSocket == NULL)
        goto fail;

    class_id = class_J4AC_android_net_LocalServerSocket.id;
    name     = "getLocalSocketAddress";
    sign     = "()Landroid/net/LocalSocketAddress;";
    class_J4AC_android_net_LocalServerSocket.method_getLocalSocketAddress = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_net_LocalServerSocket.method_getLocalSocketAddress == NULL)
        goto fail;

    class_id = class_J4AC_android_net_LocalServerSocket.id;
    name     = "accept";
    sign     = "()Landroid/net/LocalSocket;";
    class_J4AC_android_net_LocalServerSocket.method_accept = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_net_LocalServerSocket.method_accept == NULL)
        goto fail;

    class_id = class_J4AC_android_net_LocalServerSocket.id;
    name     = "close";
    sign     = "()V";
    class_J4AC_android_net_LocalServerSocket.method_close = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_net_LocalServerSocket.method_close == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "android.net.LocalServerSocket");
    ret = 0;
fail:
    return ret;
}
