/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "LocalSocketAddress.h"

typedef struct J4AC_android_net_LocalSocketAddress {
    jclass id;

    jmethodID constructor_LocalSocketAddress;
    jmethodID method_getName;
} J4AC_android_net_LocalSocketAddress;
static J4AC_android_net_LocalSocketAddress class_J4AC_android_net_LocalSocketAddress;

jobject J4AC_android_net_LocalSocketAddress__LocalSocketAddress(JNIEnv *env, jstring name)
{
    return (*env)->NewObject(env, class_J4AC_android_net_LocalSocketAddress.id, class_J4AC_android_net_LocalSocketAddress.constructor_LocalSocketAddress, name);
}

jobject J4AC_android_net_LocalSocketAddress__LocalSocketAddress__catchAll(JNIEnv *env, jstring name)
{
    jobject ret_object = J4AC_android_net_LocalSocketAddress__LocalSocketAddress(env, name);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_android_net_LocalSocketAddress__LocalSocketAddress__asGlobalRef__catchAll(JNIEnv *env, jstring name)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_android_net_LocalSocketAddress__LocalSocketAddress__catchAll(env, name);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jobject J4AC_android_net_LocalSocketAddress__LocalSocketAddress__withCString(JNIEnv *env, const char *name_cstr__)
{
    jobject ret_object = NULL;
    jstring name = NULL;

    name = (*env)->NewStringUTF(env, name_cstr__);
    if (J4A_ExceptionCheck__throwAny(env) || !name)
        goto fail;

    ret_object = J4AC_android_net_LocalSocketAddress__LocalSocketAddress(env, name);
    if (J4A_ExceptionCheck__throwAny(env) || !ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &name);
    return ret_object;
}

jobject J4AC_android_net_LocalSocketAddress__LocalSocketAddress__withCString__catchAll(JNIEnv *env, const char *name_cstr__)
{
    jobject ret_object = NULL;
    jstring name = NULL;

    name = (*env)->NewStringUTF(env, name_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !name)
        goto fail;

    ret_object = J4AC_android_net_LocalSocketAddress__LocalSocketAddress__catchAll(env, name);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &name);
    return ret_object;
}

jobject J4AC_android_net_LocalSocketAddress__LocalSocketAddress__withCString__asGlobalRef__catchAll(JNIEnv *env, const char *name_cstr__)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_android_net_LocalSocketAddress__LocalSocketAddress__withCString__catchAll(env, name_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jstring J4AC_android_net_LocalSocketAddress__getName(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_android_net_LocalSocketAddress.method_getName);
}

jstring J4AC_android_net_LocalSocketAddress__getName__catchAll(JNIEnv *env, jobject thiz)
{
    jstring ret_object = J4AC_android_net_LocalSocketAddress__getName(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jstring J4AC_android_net_LocalSocketAddress__getName__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jstring ret_object   = NULL;
    jstring local_object = J4AC_android_net_LocalSocketAddress__getName__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

const char *J4AC_android_net_LocalSocketAddress__getName__asCBuffer(JNIEnv *env, jobject thiz, char *out_buf, int out_len)
{
    const char *ret_value = NULL;
    const char *c_str     = NULL;
    jstring local_string = J4AC_android_net_LocalSocketAddress__getName(env, thiz);
    if (J4A_ExceptionCheck__throwAny(env) || !local_string) {
        goto fail;
    }

    c_str = (*env)->GetStringUTFChars(env, local_string, NULL );
    if (J4A_ExceptionCheck__throwAny(env) || !c_str) {
        goto fail;
    }

    strlcpy(out_buf, c_str, out_len);
    ret_value = out_buf;

fail:
    J4A_ReleaseStringUTFChars__p(env, local_string, &c_str);
    J4A_DeleteLocalRef__p(env, &local_string);
    return ret_value;
}

const char *J4AC_android_net_LocalSocketAddress__getName__asCBuffer__catchAll(JNIEnv *env, jobject thiz, char *out_buf, int out_len)
{
    const char *ret_value = NULL;
    const char *c_str     = NULL;
    jstring local_string = J4AC_android_net_LocalSocketAddress__getName__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_string) {
        goto fail;
    }

    c_str = (*env)->GetStringUTFChars(env, local_string, NULL );
    if (J4A_ExceptionCheck__catchAll(env) || !c_str) {
        goto fail;
    }

    strlcpy(out_buf, c_str, out_len);
    ret_value = out_buf;

fail:
    J4A_ReleaseStringUTFChars__p(env, local_string, &c_str);
    J4A_DeleteLocalRef__p(env, &local_string);
    return ret_value;
}

int J4A_loadClass__J4AC_android_net_LocalSocketAddress(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_android_net_LocalSocketAddress.id != NULL)
        return 0;

    sign = "android/net/LocalSocketAddress";
    class_J4AC_android_net_LocalSocketAddress.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_android_net_LocalSocketAddress.id == NULL)
        goto fail;

    class_id = class_J4AC_android_net_LocalSocketAddress.id;
    name     = "<init>";
    sign     = "(Ljava/lang/String;)V";
    class_J4AC_android_net_LocalSocketAddress.constructor_LocalSocketAddress = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_net_LocalSocketAddress.constructor_LocalSocketAddress == NULL)
        goto fail;

    class_id = class_J4AC_android_net_LocalSocketAddress.id;
    name     = "getName";
    sign     = "()Ljava/lang/String;";
    class_J4AC_android_net_LocalSocketAddress.method_getName = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_net_LocalSocketAddress.method_getName == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "android.net.LocalSocketAddress");
    ret = 0;
fail:
    return ret;
}
