/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__com_pananfly_loacalsocket_LocalSocketJNIHelper__H
#define J4A__com_pananfly_loacalsocket_LocalSocketJNIHelper__H

#include "j4a/j4a_base.h"
#include "config.h"

jlong J4AC_com_pananfly_loacalsocket_LocalSocketJNIHelper__mNativeInstance__get(JNIEnv *env, jobject thiz);
jlong J4AC_com_pananfly_loacalsocket_LocalSocketJNIHelper__mNativeInstance__get__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_pananfly_loacalsocket_LocalSocketJNIHelper__mNativeInstance__set(JNIEnv *env, jobject thiz, jlong value);
void J4AC_com_pananfly_loacalsocket_LocalSocketJNIHelper__mNativeInstance__set__catchAll(JNIEnv *env, jobject thiz, jlong value);
int J4A_loadClass__J4AC_com_pananfly_loacalsocket_LocalSocketJNIHelper(JNIEnv *env);

#define J4A_HAVE_SIMPLE__J4AC_com_pananfly_loacalsocket_LocalSocketJNIHelper

#define J4AC_LocalSocketJNIHelper__mNativeInstance__get J4AC_com_pananfly_loacalsocket_LocalSocketJNIHelper__mNativeInstance__get
#define J4AC_LocalSocketJNIHelper__mNativeInstance__get__catchAll J4AC_com_pananfly_loacalsocket_LocalSocketJNIHelper__mNativeInstance__get__catchAll
#define J4AC_LocalSocketJNIHelper__mNativeInstance__set J4AC_com_pananfly_loacalsocket_LocalSocketJNIHelper__mNativeInstance__set
#define J4AC_LocalSocketJNIHelper__mNativeInstance__set__catchAll J4AC_com_pananfly_loacalsocket_LocalSocketJNIHelper__mNativeInstance__set__catchAll
#define J4A_loadClass__J4AC_LocalSocketJNIHelper J4A_loadClass__J4AC_com_pananfly_loacalsocket_LocalSocketJNIHelper

#endif//J4A__com_pananfly_loacalsocket_LocalSocketJNIHelper__H
