/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "InputStream.h"

typedef struct J4AC_java_io_InputStream {
    jclass id;

    jmethodID method_read;
    jmethodID method_skip;
    jmethodID method_available;
    jmethodID method_close;
    jmethodID method_mark;
    jmethodID method_reset;
    jmethodID method_markSupported;
} J4AC_java_io_InputStream;
static J4AC_java_io_InputStream class_J4AC_java_io_InputStream;

jint J4AC_java_io_InputStream__read(JNIEnv *env, jobject thiz, jbyteArray b, jint off, jint len)
{
    return (*env)->CallIntMethod(env, thiz, class_J4AC_java_io_InputStream.method_read, b, off, len);
}

jint J4AC_java_io_InputStream__read__catchAll(JNIEnv *env, jobject thiz, jbyteArray b, jint off, jint len)
{
    jint ret_value = J4AC_java_io_InputStream__read(env, thiz, b, off, len);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jlong J4AC_java_io_InputStream__skip(JNIEnv *env, jobject thiz, jlong n)
{
    return (*env)->CallLongMethod(env, thiz, class_J4AC_java_io_InputStream.method_skip, n);
}

jlong J4AC_java_io_InputStream__skip__catchAll(JNIEnv *env, jobject thiz, jlong n)
{
    jlong ret_value = J4AC_java_io_InputStream__skip(env, thiz, n);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jint J4AC_java_io_InputStream__available(JNIEnv *env, jobject thiz)
{
    return (*env)->CallIntMethod(env, thiz, class_J4AC_java_io_InputStream.method_available);
}

jint J4AC_java_io_InputStream__available__catchAll(JNIEnv *env, jobject thiz)
{
    jint ret_value = J4AC_java_io_InputStream__available(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_java_io_InputStream__close(JNIEnv *env, jobject thiz)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_java_io_InputStream.method_close);
}

void J4AC_java_io_InputStream__close__catchAll(JNIEnv *env, jobject thiz)
{
    J4AC_java_io_InputStream__close(env, thiz);
    J4A_ExceptionCheck__catchAll(env);
}

void J4AC_java_io_InputStream__mark(JNIEnv *env, jobject thiz, jint readlimit)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_java_io_InputStream.method_mark, readlimit);
}

void J4AC_java_io_InputStream__mark__catchAll(JNIEnv *env, jobject thiz, jint readlimit)
{
    J4AC_java_io_InputStream__mark(env, thiz, readlimit);
    J4A_ExceptionCheck__catchAll(env);
}

void J4AC_java_io_InputStream__reset(JNIEnv *env, jobject thiz)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_java_io_InputStream.method_reset);
}

void J4AC_java_io_InputStream__reset__catchAll(JNIEnv *env, jobject thiz)
{
    J4AC_java_io_InputStream__reset(env, thiz);
    J4A_ExceptionCheck__catchAll(env);
}

jboolean J4AC_java_io_InputStream__markSupported(JNIEnv *env, jobject thiz)
{
    return (*env)->CallBooleanMethod(env, thiz, class_J4AC_java_io_InputStream.method_markSupported);
}

jboolean J4AC_java_io_InputStream__markSupported__catchAll(JNIEnv *env, jobject thiz)
{
    jboolean ret_value = J4AC_java_io_InputStream__markSupported(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return false;
    }

    return ret_value;
}

int J4A_loadClass__J4AC_java_io_InputStream(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_java_io_InputStream.id != NULL)
        return 0;

    sign = "java/io/InputStream";
    class_J4AC_java_io_InputStream.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_java_io_InputStream.id == NULL)
        goto fail;

    class_id = class_J4AC_java_io_InputStream.id;
    name     = "read";
    sign     = "([BII)I";
    class_J4AC_java_io_InputStream.method_read = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_java_io_InputStream.method_read == NULL)
        goto fail;

    class_id = class_J4AC_java_io_InputStream.id;
    name     = "skip";
    sign     = "(J)J";
    class_J4AC_java_io_InputStream.method_skip = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_java_io_InputStream.method_skip == NULL)
        goto fail;

    class_id = class_J4AC_java_io_InputStream.id;
    name     = "available";
    sign     = "()I";
    class_J4AC_java_io_InputStream.method_available = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_java_io_InputStream.method_available == NULL)
        goto fail;

    class_id = class_J4AC_java_io_InputStream.id;
    name     = "close";
    sign     = "()V";
    class_J4AC_java_io_InputStream.method_close = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_java_io_InputStream.method_close == NULL)
        goto fail;

    class_id = class_J4AC_java_io_InputStream.id;
    name     = "mark";
    sign     = "(I)V";
    class_J4AC_java_io_InputStream.method_mark = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_java_io_InputStream.method_mark == NULL)
        goto fail;

    class_id = class_J4AC_java_io_InputStream.id;
    name     = "reset";
    sign     = "()V";
    class_J4AC_java_io_InputStream.method_reset = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_java_io_InputStream.method_reset == NULL)
        goto fail;

    class_id = class_J4AC_java_io_InputStream.id;
    name     = "markSupported";
    sign     = "()Z";
    class_J4AC_java_io_InputStream.method_markSupported = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_java_io_InputStream.method_markSupported == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "java.io.InputStream");
    ret = 0;
fail:
    return ret;
}
