/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__java_io_OutputStream__H
#define J4A__java_io_OutputStream__H

#include "j4a/j4a_base.h"

void J4AC_java_io_OutputStream__write(JNIEnv *env, jobject thiz, jbyteArray b, jint off, jint len);
void J4AC_java_io_OutputStream__write__catchAll(JNIEnv *env, jobject thiz, jbyteArray b, jint off, jint len);
void J4AC_java_io_OutputStream__flush(JNIEnv *env, jobject thiz);
void J4AC_java_io_OutputStream__flush__catchAll(JNIEnv *env, jobject thiz);
void J4AC_java_io_OutputStream__close(JNIEnv *env, jobject thiz);
void J4AC_java_io_OutputStream__close__catchAll(JNIEnv *env, jobject thiz);
int J4A_loadClass__J4AC_java_io_OutputStream(JNIEnv *env);

#define J4A_HAVE_SIMPLE__J4AC_java_io_OutputStream

#define J4AC_OutputStream__write J4AC_java_io_OutputStream__write
#define J4AC_OutputStream__write__catchAll J4AC_java_io_OutputStream__write__catchAll
#define J4AC_OutputStream__flush J4AC_java_io_OutputStream__flush
#define J4AC_OutputStream__flush__catchAll J4AC_java_io_OutputStream__flush__catchAll
#define J4AC_OutputStream__close J4AC_java_io_OutputStream__close
#define J4AC_OutputStream__close__catchAll J4AC_java_io_OutputStream__close__catchAll
#define J4A_loadClass__J4AC_OutputStream J4A_loadClass__J4AC_java_io_OutputStream

#endif//J4A__java_io_OutputStream__H
